# Generated by Django 3.0.4 on 2020-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20200703_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Mobile_Number', models.IntegerField()),
                ('Aadhar_no', models.IntegerField()),
            ],
        ),
    ]
