# Generated by Django 3.0.4 on 2020-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcrop',
            name='addFarmerID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
