# Generated by Django 3.0.4 on 2020-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20200704_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcrop',
            name='addFarmerID',
            field=models.CharField(max_length=100),
        ),
    ]
