# Generated by Django 3.0.4 on 2020-07-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_addcrop_addcropquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcrop',
            name='addFarmerID',
            field=models.IntegerField(),
        ),
    ]
