# Generated by Django 3.0.4 on 2020-07-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_auto_20200704_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcrop',
            name='addPostNumber',
        ),
        migrations.AddField(
            model_name='addcrop',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
